# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: jenkins-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]